python train_MPN.py
python train_MPN2.py
python train_MPN3.py
python train_MPN4.py
python train_MPN5.py
python train_MPN6.py
python train_MPN7.py
python train_MPNOne.py
python train_MPNOne2.py
python train_MPNOne3.py
python train_MPNOne4.py
python train_MPNOne5.py
python train_MPNOne6.py
python train_MPNOne7.py
python train_MPNNoMP.py
python train_MPNNoMP2.py
python train_MPNNoMP3.py
python train_MPNNoMP4.py
python train_MPNNoMP5.py
python train_MPNNoMP6.py
python train_MPNNoMP7.py
python train_MPNRemoveBoth.py
python train_MPNRemoveBoth2.py
python train_MPNRemoveBoth3.py
python train_MPNRemoveBoth4.py
python train_MPNRemoveBoth5.py
python train_MPNRemoveBoth6.py
python train_MPNRemoveBoth7.py